server:
  port: 8090

spring:
  application:
    name: template
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  sql:
#    init:
#      mode: always

redis:
  host: localhost
  port: 6379
